In [2]:
import numpy as np
import matplotlib.pyplot as plt



# Notebook for 1. Introduction to python from DataCamp 

### 1.1 Python Basics

In [3]:


# Example, do not modify!
print(5 / 8)

# Print the sum of 7 and 10
print(7+10)


# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# How much is your $100 worth after 7 years?
print(100*1.1**7)


# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = savings*growth_multiplier**7

# Print out result
print(result)

# Create a variable desc
desc = "compound interest"

# Create a variable profitable
profitable = True


# Assign product of growth_multiplier and savings to year1
year1 = savings * growth_multiplier

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc

# Print out doubledesc
print(doubledesc)


result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

0.625
17
10
0
15
5.0
4
16
194.87171000000012
194.87171000000012
<class 'float'>
compound interestcompound interest
I started with $100 and now have $194.87171000000012. Awesome!


### 1.2 Python Lists


In [4]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)

# Adapt list areas
areas = ["hallway",hall,"kitchen", kit, "living room", liv,"bedroom", bed, "bathroom", bath]

# Print areas
print(areas)



[11.25, 18.0, 20.0, 10.75, 9.5]
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [5]:
# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house)) 

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


In [6]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [7]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3]+areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [8]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs
print(downstairs,upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0] ['bedroom', 10.75, 'bathroom', 9.5]


In [9]:
# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage",15.45]

In [10]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


### 1.3 Functions and Packages

In [11]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1

print(type(var1))
# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


In [12]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full

full = first + second

# Sort full in descending order: full_sorted

full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


In [13]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up

print(place, place_up)
# Print out the number of o's in place
print(place.count('o'))

poolhouse POOLHOUSE
3


In [14]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0

print(areas.index(20))
# Print out how often 9.50 appears in areas
print(areas.count(9.5))

2
1


In [15]:
# Use append twice to add poolhouse and garage size

areas.append(24.5)
areas.append(15.45)
# Print out areas

print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas

print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [16]:
# Definition of radius
r = 0.43

# Import the math package
import math as mt

# Calculate C
C = 2*mt.pi*r

# Calculate A
A = mt.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [17]:
# Definition of radius
r = 192500

# Import radians function of math package

from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.

dist = r * radians(12)

# Print out dist

print(dist)

40317.10572106901


### 1.4 NumPy


In [18]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball

np_baseball = np.array(baseball)

# Print out type of np_baseball

print(type(np_baseball))

<class 'numpy.ndarray'>


In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('baseball.csv', usecols=['Height', 'Weight','Age'])

In [21]:
height_in = []
weight_lb = []
age = []
for i in df.values:
    height_in.append(i[0])
    weight_lb.append(i[1])
    age.append(i[2])

In [22]:
# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = 0.0254 * np_height_in

# Print np_height_m

print(np_height_m)


[74. 74. 72. ... 75. 75. 73.]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [23]:
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi

bmi = np_weight_kg/np_height_m**2

# Print out bmi

print(bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


In [24]:
# height and weight are available as a regular lists



# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array

light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])


[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [25]:
# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50

print(np_weight_lb[50])
# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

200.0
[73. 74. 72. 73. 69. 72. 73. 75. 75. 73. 72.]


In [26]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)



<class 'numpy.ndarray'>
(4, 2)


In [27]:
# Print out the shape of np_baseball

np_baseball = df.values
print(np_baseball.shape)

(1015, 3)


In [28]:
# Print out the 50th row of np_baseball

print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight_lb

np_weight_lb = np_baseball[:,1]


# Print out height of 124th player
print(np_baseball[123,0])

[ 70.   195.    30.69]
75.0


In [29]:
# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6896551724138
74.0


In [30]:
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


#### Fifa dataset

In [31]:
dff = pd.read_csv('fifa.csv', usecols=[' position', ' height'])

In [32]:
positions = []
heights = []
for i in dff.values:
    positions.append(i[0])
    heights.append(i[1])


In [33]:
# Convert positions and heights to numpy arrays: np_positions, np_heights

np_positions, np_heights = np.array(positions) , np.array(heights)

# Heights of the goalkeepers: gk_heights
np_gkp = np_positions == " GK"
gk_heights = np_heights[np_gkp]
# Heights of the other players: other_heights
other_heights = np_heights[np_gkp==False]

# Print out the median height of goalkeepers. Replace 'None'
meangk = np.median(gk_heights)
print("Median height of goalkeepers: " + str(meangk))

# Print out the median height of other players. Replace 'None'
meannogk = np.median(other_heights)

print("Median height of other players: " + str(meannogk))

Median height of goalkeepers: 188.0
Median height of other players: 181.0
